spring:
  application:
    name: backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_app
    username: postgres
    password: ninjacongxyz9059
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
jwt:
  secret: tmDe/9eVc0GJE1wSP3oqyH8LxuQmNUThqW4pBVlbinY=
  expiration: 86400000

cloudinary:
  cloud-name: dwfcqm6xb
  api-key: 182668721548126
  api-secret: FdSaoAq4o5CdHYhhyTQoFb6ZLNk

